service: bookme-staging

plugins:
- serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: staging
  region: ap-northeast-1

functions:
  graphql:
    handler: handler.server
    events:
    - http:
        path: /
        method: post
        cors: true
  playground:
    handler: handler.playground
    events:
    - http:
        path: /
        method: get
        cors: true
